apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j8cxq6dss-python
  janus-idp.io/tekton: j8cxq6dss-python
  backstage.io/kubernetes-id: j8cxq6dss-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j8cxq6dss-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
